// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",

    // "npx prisma db seed" bu komutu calistirir.
    // Prisma 7'de seed ayari package.json'dan BURAYA tasindi --
    // eski ogreticilerde package.json icinde "prisma": { "seed": ... }
    // gorursen, yeri artik burasi.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
